### PR TITLE
WIP: Expansion of ASC 0

### PR DESCRIPTION
**Pull request by WarmCyan**
I'm working on expanding some of the content in ASC 0. In particular, I think we might want the introduction section (on this and future documents) to contain a decent amount of background on the problem, and then, like in RFC, put an abstract above the TOC with a short description of the document.

(Don't merge this yet, I'll continue to expand on some of the sections. Submitting a PR now so that I can become more familiar with the PR process, as well as initiating a discussion point for ASC 0.)

### CODE REVIEW

**Comment by WarmCyan** [comment]
Ah, yes, so a convention that gitlab uses (which github doesn't, but I think we can still use informally) is to disallow the merging of PR's that begin with `WIP:`. Github doesn't seem to have this restriction, but I think we should follow the convention that PR's with WIP in the title shouldn't be merged, and the submitter can edit the title once they feel it's ready

**Comment by WarmCyan** [comment]
I think there are a few things that should be discussed regarding syntax conventions of the RST files:

* Section header characters! I love that RST's allow pretty much whatever, but just looking at them as-is with the proposed convention in this document in a non RTF editor makes it difficult to tell what's actually a subsection and what isn't. 

I propose (open for discussion) this hierarchy, based loosely off of visible character height or density:
1. For the document title, use `###` over-and-under line:
```
####################################################
AWDE Standards Core Standard
####################################################
```
2. For primary section titles, use `###` underline
```
Abstract
####################################################
```
3. For subsection titles, use `===` underline
```
Motivation
====================================================
```
4. For subsubsection titles, use `---` underline
```
Definition Imports
----------------------------------------------------
```

* Line spacing conventions. I vote no blank line after the underline delimiter, and two blank lines before a section header. (Again for the sake of readability in an editor)
```
(previous things)


New Section
###################################
New section content and things
```

* I remembered that vim modelines are a thing, and since I'm pretty sure our `.vimrc`'s don't match, I vote we always keep the last line as a vim modeline! (see commit for an example if you've never heard of them, they're actually really cool and I think I'm going to start using them in most of my work that other people might touch)

* I think we might also want a last-updated property at the top (added in commit)

Finally, a question - how do you intend version numbers to work?

**Comment by AwdeDarkar** [comment]
I like the proposed hierarchy for sections, but I think the 'abstract' section is redundant with the summary in the 'introduction' section. We could drop the summary in the introduction or maybe move the introduction above the table of contents (or make the table of contents a subsection of introduction) but I don't think we want both a summary and an abstract.

**Comment by WarmCyan** [comment]
Hmm, maybe we should have a more clearly defined format for how the introduction is written then? 

My thinking was that the abstract/intro wouldn't be redundant: I really like the idea of having a 2-3 sentence explanation summarizing what the document is, which can be read in a quick glance (hence the abstract.) The introduction then, rather than being a summary of what the document is, would be more of an overall background or context explanation, (like commit [0ecd75](https://github.com/AwdeDarkar/asc/pull/1/commits/0ecd75c85a72c24ba83673e30a2f18e2ea15f64a)) with the motivation section describing the specific reason why we think what's specified in the document will fix the issue or problem detailed in the intro.

I could see those being combined, where maybe intro has a subsection that's an "executive summary" type deal, or even just always assuming that the first paragraph in the intro will always be the 2-3 sentence summary of contents, I just felt that an abstract section like in RFC's delineates that a bit more logically

Thoughts?

**Comment by AwdeDarkar** [comment]
Looking at it now I think you're right. While Abstract and Introduction do still feel redundant for _this particular_ ASC, in general they do serve distinct purposes. I'm good with everything you've come up with so far for merging this into master.

**Pull request merged**
